### ISSUE TITLE
Add Back GitHub Notifications To Slack

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/giving-backend#32]
This comes out of seeing a Rails security update yesterday but not having a way the DE team is alerted...I just saw it while browsing developer channels. Someone gave me links to various Rails security-related message boards.

Then, I remembered Dependabot includes security updates, and I also remembered that the Advancement Central Slack used to have a #github channel. If that channel were brought back, it would fit the "send security updates to notification/alerts channel".

Rails links:
- https://discuss.rubyonrails.org/c/security-announcements/9
- https://rubyonrails.org/security/
- https://groups.google.com/g/rubyonrails-security?pli=1

Dependabot:
- https://github.com/integrations/slack#branch-filters-for-commit

AC:
- [x] Slack channel(s) get notified when security updates are released
- [x] Process is documented in `github-docs` repo in the readme's GH admin section
- [x] Upgrade Slack Github app from legacy version

**Comment by alexfinnarn** [comment]
<img width="499" alt="Screen Shot 2021-06-02 at 11 44 13 AM" src="https://user-images.githubusercontent.com/3640707/120519176-56994100-c3a0-11eb-9fb5-e92d760f2144.png">

@mattroush I think this will be easy to upgrade, create a channel, and then subscribe to relevant repositories. However, I don't want to do this without asking first as I never set up the original GitHub notifications...which I think was put into one channel. 

More info: https://github.com/integrations/slack/blob/master/README.md#moving-away-from-the-legacy-workspace-app-model-in-slack

**Comment by mattroush** [comment]
@alexfinnarn [The app has been added](https://advancementcentral.slack.com/archives/D0242A06B0B) and I've "invited" it to [#de-service-alerts channel](https://advancementcentral.slack.com/archives/G01F4TM3QE6). Assume you can configure the subscriptions/notifications from there? If you need me to do something else or make a call on something, let me know.

**Comment by alexfinnarn** [comment]
Thanks! I'll have to look up how to just add security notices to that one. Would it be helpful to have a general channel for GitHub activity?

**Comment by mattroush** [comment]
Yea, why not -- if we decide later that it's not helpful, we can always disable it then.

**Comment by alexfinnarn** [comment]
Let's see if this works now...

**Comment by alexfinnarn** [comment]
I guess it logs close/reopen but no comments...

**Comment by alexfinnarn** [comment]
now I see comments?

**Comment by alexfinnarn** [comment]
I added an issue to figure out how to subscribe to security alerts https://github.com/integrations/slack/issues/1224

**Comment by alexfinnarn** [comment]
more notifications can be added from repos, but a channel exists now with most notifications.
